sonar.projectKey=yggdrasil-au_RemakeEngine
sonar.organization=yggdrasil-au
sonar.projectName=RemakeEngine
sonar.projectVersion=1.7.0

# Source/test layout
sonar.sources=Engine/
#sonar.tests=.

# Mark tests so Sonar doesn’t treat them as source
sonar.test.inclusions=**/tests/**,**/*_test.py,**/test_*.py

# Exclusions (single line; includes your runtime dir)
sonar.exclusions=runtime/**,**/venv/**,**/.venv/**,**/site-packages/**,**/build/**,**/dist/**,**/.tox/**


sonar.python.coverage.reportPaths=coverage.xml

# Optional: copy–paste detection exclusions
sonar.cpd.exclusions=runtime/**
