[pytest]
norecursedirs = venv .venv build dist .tox runtime blender dev reverse_engineering_stuff .history
addopts = --ignore=runtime/ --ignore=blender/ --ignore=reverse_engineering_stuff/ --ignore=dev/ --ignore=.history/ --ignore=RemakeRegistry
pythonpath = Engine
source = Engine