[pytest]
norecursedirs = venv .venv build dist .tox runtime blender-4.0.2-windows-x64 dev reverse_engineering_stuff .history
addopts = --ignore=runtime --ignore=blender-4.0.2-windows-x64 --ignore=reverse_engineering_stuff --ignore=dev --ignore=.history
pythonpath = .
