[tox]
envlist = py311
skipsdist = True

[testenv]
deps =
    tests
commands =
    coverage run -m pytest tests/
    coverage xml

[coverage:run]
branch = True
relative_files = True
source =
    .
    Source
    Utils
    Tools
    RemakeRegistry

[coverage:report]
omit =
    */OldModules/*
    */OldRemakeRegistry/*
    */reverse_engineering_docs/*
    */Tools/Blender/*

