<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <OutputType>Library</OutputType>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>disable</ImplicitUsings>
        <DebugType>embedded</DebugType>
        <Platforms>AnyCPU;x64</Platforms>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Shared\EngineNet.Shared.csproj" />
        <ProjectReference Include="..\Data\EngineNet.Core.Data.csproj" />
        <ProjectReference Include="..\ExternalTools\EngineNet.Core.ExternalTools.csproj" />
        <ProjectReference Include="..\Utils\EngineNet.Core.Utils.csproj" />
        <ProjectReference Include="..\Abstractions\EngineNet.Core.Abstractions.csproj" />
    </ItemGroup>

    <PropertyGroup>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    </PropertyGroup>

</Project>
