--[[
Demo build script for the RemakeEngine demo module.

Responsibilities:
1) Generate a minimal Godot project in {{Game_Root}}/TMP/godot-demo-project.
2) Generate module-root game.toml with exe pointing at project.godot.
3) Optionally run a light Godot validation launch.

References:
- demo lua_feature_demo.lua for SDK usage patterns.
- TheSimpsonsGame-PS3 godot-init script for tool/process patterns.
]]

local function ParseArgs(List)
	local Opts = {
		OutputRoot = nil,
		ProjectName = 'DemoGame',
		Note = 'Generated by demo/scripts/build.lua',
		SkipGodotRun = false,
	}

	local Index = 1
	while Index <= #List do
		local Key = List[Index]
		local NextValue = List[Index + 1]

		if Key == '--output' and NextValue then
			Opts.OutputRoot = NextValue
			Index = Index + 2
		elseif Key == '--project-name' and NextValue then
			Opts.ProjectName = NextValue
			Index = Index + 2
		elseif Key == '--note' and NextValue then
			Opts.Note = NextValue
			Index = Index + 2
		elseif Key == '--skip-godot-run' then
			Opts.SkipGodotRun = true
			Index = Index + 1
		else
			Index = Index + 1
		end
	end

	return Opts
end

local function Info(Message)
	sdk.color_print('cyan', Message)
	Diagnostics.Log('[demo-build] INFO: ' .. Message)
end

local function WarnMessage(Message)
	sdk.color_print('yellow', Message)
	Diagnostics.Log('[demo-build] WARN: ' .. Message)
	warn(Message)
end

local function Fail(Message)
	sdk.color_print('red', Message)
	Diagnostics.Log('[demo-build] ERROR: ' .. Message)
	error(Message)
end

local function EnsureDirectory(Path)
	local Ok = sdk.ensure_dir(Path)
	if not Ok then
		Fail('Failed to create directory: ' .. tostring(Path))
	end
end

local function WriteTextFile(Path, Content)
	local Ok = sdk.write_file(Path, Content)
	if not Ok then
		Fail('Failed to write file: ' .. tostring(Path))
	end
end

local function ResolveGodotExecutable()
	local ToolFn = rawget(_G, 'tool')
	if type(ToolFn) ~= 'function' then
		Fail('Global tool(name) resolver is unavailable.')
	end

	local GodotPath = ToolFn('Godot')
	if not GodotPath or GodotPath == '' then
		Fail('Godot executable not found via tool("Godot").')
	end

	if not sdk.is_file(GodotPath) then
		Fail('Resolved Godot path is not a file: ' .. tostring(GodotPath))
	end

	return GodotPath
end

local function BuildProjectGodot(ProjectName)
	return table.concat({
		'; Engine configuration file.',
		'; It is best edited using the editor UI and not directly,',
		'; because the parameters that go here are not all obvious.',
		';',
		'; Format:',
		';   [section] ; section goes between []',
		';   param=value ; assign values to parameters',
		'',
		'config_version=5',
		'',
		'[application]',
		string.format('config/name="%s"', ProjectName),
		'run/main_scene="res://scenes/main.tscn"',
		'config/features=PackedStringArray("4.5")',
		'',
		'[display]',
		'window/size/viewport_width=1280',
		'window/size/viewport_height=720',
		'window/stretch/mode="canvas_items"',
		'',
		'[rendering]',
		'renderer/rendering_method="gl_compatibility"',
		''
	}, '\n')
end

local function BuildMainScene()
	return table.concat({
		'[gd_scene load_steps=2 format=3]',
		'',
		'[ext_resource type="Script" path="res://scripts/main.gd" id="1"]',
		'',
		'[node name="Main" type="Node2D"]',
		'script = ExtResource("1")',
		'',
		'[node name="Label" type="Label" parent="."]',
		'offset_left = 64.0',
		'offset_top = 64.0',
		'offset_right = 840.0',
		'offset_bottom = 160.0',
		'text = "RemakeEngine demo build.lua generated this Godot scene."',
		'theme_override_font_sizes/font_size = 24',
		''
	}, '\n')
end

local function BuildMainScript(Note)
	return table.concat({
		'extends Node2D',
		'',
		'func _ready() -> void:',
		'    print("RemakeEngine Godot demo project is ready.")',
		string.format('    print("Build note: %s")', tostring(Note):gsub('"', '\\"')),
		'    var label := get_node_or_null("Label")',
		'    if label and label is Label:',
		'        label.text = "Demo scene running from generated project.godot"',
		''
	}, '\n')
end

local function BuildGameToml(ProjectName)
	local ExePath = string.format('{{Game_Root}}/TMP/godot-demo-project/%s/project.godot', ProjectName)
	return table.concat({
		'# Auto-generated by EngineApps/Games/demo/scripts/build.lua',
		'title = "RemakeEngine Demo Godot Game"',
		'name = "demo"',
		string.format('exe = "%s"', ExePath),
		''
	}, '\n')
end

local function TryRunGodot(GodotExe, ProjectRoot)
	local VersionResult = sdk.run_process({ GodotExe, '--version' }, {
		capture_stdout = true,
		capture_stderr = true,
		timeout_ms = 8000,
	})

	if VersionResult and VersionResult.success then
		local VersionText = VersionResult.stdout and VersionResult.stdout:gsub('%s+$', '') or 'unknown'
		Info('Godot version check passed: ' .. tostring(VersionText))
	else
		WarnMessage('Godot version check failed; continuing with project generation.')
	end

	local ProbeResult = sdk.run_process({ GodotExe, '--headless', '--path', ProjectRoot, '--quit' }, {
		capture_stdout = true,
		capture_stderr = true,
		timeout_ms = 30000,
	})

	if ProbeResult and ProbeResult.success then
		Info('Godot project probe succeeded (--headless --path --quit).')
		return true, ProbeResult
	end

	WarnMessage('Godot project probe did not report success. Project files were still generated.')
	return false, ProbeResult
end

local function Main()
	local Opts = ParseArgs(argv)

	local ModuleRoot = type(Game_Root) == 'string' and Game_Root or '.'
	local OutputRoot = Opts.OutputRoot or join(ModuleRoot, 'TMP', 'godot-demo-project')
	local ProjectRoot = join(OutputRoot, Opts.ProjectName)
	local ScenesDir = join(ProjectRoot, 'scenes')
	local ScriptsDir = join(ProjectRoot, 'scripts')
	local AssetsDir = join(ProjectRoot, 'assets')
	local DataDir = join(ProjectRoot, 'data')

	local ProjectGodotPath = join(ProjectRoot, 'project.godot')
	local MainScenePath = join(ScenesDir, 'main.tscn')
	local MainScriptPath = join(ScriptsDir, 'main.gd')
	local AssetReadmePath = join(AssetsDir, 'README.txt')
	local DataJsonPath = join(DataDir, 'demo_metadata.json')
	local BuildReportPath = join(OutputRoot, 'build-report.toml')
	local ModuleGameTomlPath = join(ModuleRoot, 'game.toml')

	progress.start(7, 'demo/build.lua: generate Godot demo game')

	progress.step('Resolving Godot tool and preparing output folders')
	local GodotExe = ResolveGodotExecutable()
	EnsureDirectory(OutputRoot)
	EnsureDirectory(ProjectRoot)
	EnsureDirectory(ScenesDir)
	EnsureDirectory(ScriptsDir)
	EnsureDirectory(AssetsDir)
	EnsureDirectory(DataDir)

	progress.step('Generating Godot project files')
	WriteTextFile(ProjectGodotPath, BuildProjectGodot(Opts.ProjectName))
	WriteTextFile(MainScenePath, BuildMainScene())
	WriteTextFile(MainScriptPath, BuildMainScript(Opts.Note))

	progress.step('Generating sample demo assets/placeholders')
	WriteTextFile(AssetReadmePath, 'This folder is intentionally simple for the demo build output.\n')
	local MetadataJson = sdk.text.json.encode({
		generated_by = 'demo/scripts/build.lua',
		project_name = Opts.ProjectName,
		output_root = OutputRoot,
		note = Opts.Note,
		generated_at = os.date('!%Y-%m-%dT%H:%M:%SZ')
	}, { indent = true })
	WriteTextFile(DataJsonPath, MetadataJson)

	progress.step('Writing module-root game.toml launch metadata')
	WriteTextFile(ModuleGameTomlPath, BuildGameToml(Opts.ProjectName))

	local ProbeSuccess = false
	local ProbeResult = nil
	if Opts.SkipGodotRun then
		progress.step('Skipping Godot probe (--skip-godot-run)')
		WarnMessage('Skipping Godot run validation by request.')
	else
		progress.step('Running Godot probe for generated project')
		ProbeSuccess, ProbeResult = TryRunGodot(GodotExe, ProjectRoot)
	end

	progress.step('Writing build report artifact')
	sdk.toml_write_file(BuildReportPath, {
		demo = {
			name = 'godot-demo-build',
			project_name = Opts.ProjectName,
			generated_at_utc = os.date('!%Y-%m-%dT%H:%M:%SZ'),
			note = Opts.Note,
		},
		paths = {
			module_root = ModuleRoot,
			output_root = OutputRoot,
			project_root = ProjectRoot,
			project_file = ProjectGodotPath,
			game_toml = ModuleGameTomlPath,
		},
		godot = {
			executable = GodotExe,
			probe_success = ProbeSuccess,
			probe_exit_code = ProbeResult and ProbeResult.exit_code or -1,
		},
	})

	progress.step('build.lua complete')
	progress.finish()

	sdk.color_print('green', 'Demo Godot project generated at: ' .. ProjectRoot)
	sdk.color_print('green', 'game.toml generated at: ' .. ModuleGameTomlPath)
end

Main()




