name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
    
      - name: Install tox and dependencies
        run: pip install tox
    
      - name: Run tests and generate coverage
        run: tox -e py  # tox creates coverage.xml
    
      - name: Prepare coverage report
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path .sonarqube/out
          Move-Item -Path coverage.xml -Destination .sonarqube/out/coverage.xml

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.python.coverage.reportPaths=.sonarqube/out/coverage.xml
            -Dsonar.exclusions=reverse_engineering/**
